#!/usr/bin/env bash

source /home/juan_francisco_chango/envs/tf-gpu/bin/activate
python3 12_continue_train_model_rich_cnn_lstm_portuguese.py 11
python3 12_continue_train_model_rich_cnn_lstm_portuguese.py 12
python3 12_continue_train_model_rich_cnn_lstm_portuguese.py 13
python3 12_continue_train_model_rich_cnn_lstm_portuguese.py 14
python3 12_continue_train_model_rich_cnn_lstm_portuguese.py 15
python3 12_continue_train_model_rich_cnn_lstm_portuguese.py 16
python3 12_continue_train_model_rich_cnn_lstm_portuguese.py 17
python3 12_continue_train_model_rich_cnn_lstm_portuguese.py 18
python3 12_continue_train_model_rich_cnn_lstm_portuguese.py 19